# Generated by Django 5.2.7 on 2025-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_pricing_and_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
